In [1]:
import modern_robotics as mr
import numpy as np 
import math

In [3]:
R = np.array([[0, 0, 1],[-1, 0, 0],[0, -1, 0]])
ans = mr.MatrixLog3(R)
ans

array([[ 0.        ,  1.20919958,  1.20919958],
       [-1.20919958,  0.        ,  1.20919958],
       [-1.20919958, -1.20919958,  0.        ]])

In [4]:
R = np.array([[0, 0.5, -1],[-0.5, 0, 2],[1, -2, 0]])
ans = mr.MatrixExp3(R)
ans

array([[ 0.60482045,  0.796274  , -0.01182979],
       [ 0.46830057, -0.34361048,  0.81401868],
       [ 0.64411707, -0.49787504, -0.58071821]])

In [5]:
omega = np.array([1, 2, 0.5]).T
mr.VecToso3(omega)

array([[ 0. , -0.5,  2. ],
       [ 0.5,  0. , -1. ],
       [-2. ,  1. ,  0. ]])

In [6]:
omega = np.array([1, 2, 0])
omegamat= mr.VecToso3(omega)
mr.MatrixExp3(omegamat)

array([[-0.2938183 ,  0.64690915,  0.70368982],
       [ 0.64690915,  0.67654542, -0.35184491],
       [-0.70368982,  0.35184491, -0.61727288]])

In [13]:
R = np.array([[0, 1, 0],[0, 0, 1],[1, 0, 0]])
omg = mr.MatrixLog3(R)
omega = mr.so3ToVec(omg)
omghat, theta = mr.AxisAng3(omega)
print(theta)


2.0943951023931957


In [68]:
##Question 1 on Chapters 3.3, 3.4 
#Write the transformation matrix T_sa
np.array([[0, -1,  0, 0],
          [0,  0, -1, 0],
          [1,  0,  0, 1],
          [0,  0,  0, 1]])

#Write the transformation matrix T_sb
R_sb = np.array([[1, 0, 0],
                 [0, 0, 1],
                 [0, -1, 0]])
p_sb = np.array([0, 2, 0]).T
T_sb = mr.RpToTrans(R_sb, p_sb)
invT_sb = mr.TransInv(T_sb)

#Write the transformation matrix T_ab 
R_sa = R_sb = np.array([[0, -1, 0],
                        [0, 0, -1],
                        [1, 0, 0]])
p_sa = np.array([0, 0, 1]).T
T_sa = mr.RpToTrans(R_sa, p_sa)
invT_sa = mr.TransInv(T_sa)
T_ab = invT_sa @ T_sb

#Use T_sb to change the representation of 
p_b = np.array([1, 2, 3, 1]).T #transform to homogenous coordinates
p_s = T_sb @ p_b

#What is the representation of V_a?
V_s = np.array([3,2,1,-1,-2,-3]).T
V_a = mr.Adjoint(invT_sa) @ V_s

#Calculate the matrix logarithm of T_sa. Write the rotation amount of theta in rad.
T6_sa = mr.MatrixLog6(T_sa)
T6_vec = mr.se3ToVec(T6_sa)
S_sa, theta_sa = mr.AxisAng6(T6_vec)
print(theta_sa)

#Calculate the matrix exponential
motion9 = np.array([0, 1, 2, 3, 0, 0]).T
motion9_mat = mr.VecTose3(motion9)
SEmotion9= mr.MatrixExp6(motion9_mat)

#Use T_sb to change the representation of the wrench to {s} coordinates
w_b = np.array([1, 0, 0, 2, 1, 0]).T
A_sb = mr.Adjoint(invT_sb).T
w_s = A_sb @ w_b

#Use TransInv to calculate the inverse of the matrix
T11 = np.array([[0, -1, 0, 3],
                [1,  0, 0, 0],
                [0,  0, 1, 1],
                [0,  0, 0, 1]])
invT11 = mr.TransInv(T11)

#Write the se3 matrix corresponding to the twist 
v12 = np.array([1,0,0,0,2,3]).T
v12_mat = mr.VecTose3(v12)

#Calculate the normalized screw axis 
p13 = np.array([0, 0 ,2])
s13 = np.array([1, 0, 0])
h13 = 1
screw13 = mr.ScrewToAxis(p13, s13, h13)

#Use MatrixExp6 to calculate the homogenous transformation matrix 
mat14 = np.array([[0, -1.5708, 0, 2.3562],
                  [1.578, 0, 0, -2.3562],
                  [0, 0, 0, 1],
                  [0, 0, 0, 0]])
expmat14 = mr.MatrixExp6(mat14)
roundedemat14 = np.round(expmat14)

logmat15 = mr.MatrixLog6(roundedemat14)

2.0943951023931957


In [44]:
#Quiz on Chapter 5
#Question 1
s_1 = np.array([0, 0, 1, 0, 0, 0])
s_2 = np.array([0, 0, 1, 0,-1, 0])
s_3 = np.array([0, 0, 1, math.sin(math.radians(45)) , -(1 + math.cos(math.radians(45))), 0])
j_s = np.zeros((6,3))
j_s[:,0] = s_1
j_s[:,1] = s_2
j_s[:,2] = s_3
# print(j_s)
# print(j_s.T @ np.array([0, 0, 0, 2, 0, 0]).T)

#Question2
t1, t2  = 0, 0
t3 = np.pi/2
t4 = -np.pi/2
j_b = np.array([[0, 0, 0, 0],
                [0, 0, 0, 0],
                [1, 1, 1, 1],
                [np.sin(t4) + np.sin(t3 + t4) + np.sin(t2+t3+t4), np.sin(t4) + np.sin(t3 + t4), np.sin(t4), 0],
                [1 + np.cos(t4)+ np.cos(t3+t4) + np.cos(t2 + t3 + t4), 1 + np.cos(t4) + np.cos(t3 + t4), 1 + np.cos(t4), 1],
                [0, 0, 0, 0]])
# print(j_b)
# j_b.T @ np.array([0, 0, 10, 10, 10, 0]).T

#Question 3
j_b = np.zeros((6,3))
b_1 = np.array([0, 0, 1, 0, 0, 0])
b_2 = np.array([1, 0, 0, 0, 2, 0])
b_3 = np.array([0, 0, 0, 0, 1, 0])
j_b[:,0] = b_1
j_b[:,1] = b_2
j_b[:,2] = b_3

t_list = np.array([math.radians(90), math.radians(90), 1])
j_space = mr.JacobianSpace(j_b, t_list)
# print(j_space)

#Question 4
j_b = np.zeros((6,3))
b_1 = np.array([0, 1, 0, 3, 0, 0])
b_2 = np.array([-1, 0, 0, 0, 3, 0])
b_3 = np.array([0, 0, 0, 0, 0, 1])
j_b[:,0] = b_1
j_b[:,1] = b_2
j_b[:,2] = b_3

t_list = np.array([math.radians(90), math.radians(90), 1])
j_body = mr.JacobianBody(j_b, t_list)
# print(j_body)

#Question 5    
j_b = np.array([[     0,     -1,     0,      0,    -1,     0, 0],
                [     0,      0,     1,      0,     0,     1, 0],
                [     1,      0,     0,      1,     0,     0, 1],
                [-0.105,      0, 0.006, -0.045,     0, 0.006, 0],
                [-0.889,  0.006,     0, -0.844, 0.006,     0, 0],
                [     0, -0.105, 0.889,      0,     0,     0, 0]])

j_v = j_b[3:6,:]
A = j_v @ j_v.T
#Find the eigenvalues and vectors for the linear velocity Jacobian
eig_val, eig_vec = np.linalg.eig(A)
#Find the unit vector of the longest eigenval 
u_v = eig_vec[:, 1]
#Normalize this vector to find the unit direction
u_v_norm = u_v / np.linalg.norm(u_v)
#Find the length of the longest principal axis.
long_val = math.sqrt(eig_val[1])
# print(long_val)
# print(eig_val)
# print(u_v_norm)
# print(eig_vec)
# print(u_v)
# print(j_v)


In [61]:
#Quiz on the Newton-Raphson Method
#Assign our starter variables.
# xy = (x_0, y_0)
xy = np.array([1, 1])

#How many times do we want to iterate forward? i = (x**i, y**i)
for i in range(2):
    #Solve the function at the current position.
    f_xy = np.array([xy[0]**2 - 9,
                     xy[1]**2 - 4 ]).T

    #This is the slope at the current point. This is also the Jacobian solved at (x_0, y_0)
    df_xy = np.array([[2 * xy[0], 0],
                      [0, 2 * xy[1]]])

    #We need the inverted Jacobian to solve this matrix, 
    #BUT we don't have a Jacobian that is invertable? (Might not be true but either way, psuedoinverse
    #usually is a decent approximation) and provides robustness in method. We rely 
    #on the pseudoinverse of the Jacobian instead. 

    #We need to find the Delta to move our point forward. 
    #Delta = pJ**(-1)(theta_0) (-1 * slope)
    pseudoInv = np.linalg.pinv(-1 * df_xy)
    Delta = pseudoInv @ f_xy

    #Find our new point and repeat the process.
    xy = xy + Delta 


# print(pseudoInv.shape)
# print(Delta)
# print(xy)
# print(i)

#Question2
#Decided to list the Screw Axes in the Spaces frame, enabling us to use the IKinSpace
screw_1 = np.array([0, 0, 1, 0,  0, 0])
screw_2 = np.array([0, 0, 1, 0, -1, 0])
screw_3 = np.array([0, 0, 1, 0, -2, 0])
slist = np.zeros((6, 3))
slist[:, 0] = screw_1
slist[:, 1] = screw_2
slist[:, 2] = screw_3

#Home Configuration of the Machine
M = np.array([[1, 0, 0, 3],
               [0, 1, 0, 0],
               [0, 0, 1, 0],
               [0, 0, 0, 1]])

#Creation of the Transformation Matrix we want to achieve
T_sd = np.array([[-0.585, -0.811,  0, 0.076],
                 [ 0.811, -0.585,  0, 2.608],
                 [     0,      0,  1,     0],
                 [     0,      0,  0,     1]])

#Creation of our original guess
theta_0 = np.array([0.7854, 0.7854, 0.7854])

e_w = 0.001
e_v = 0.0001

[thetalist,success] = mr.IKinSpace(slist,M,T_sd,theta_0,e_w,e_v)
print(thetalist)

[0.92519754 0.58622516 0.68427316]


In [79]:
# I_xx =  mass_c * (3 * r_c **2 + h **2) / 12 + 2 * mass_s * (r_s **2 + r_s **2) / 5
# I_yy =  mass_c * (3 * r_c **2 + h **2) / 12 + 2 * mass_s * (r_s **2 + r_s **2) / 5
# I_zz =  mass_c * (r_c **2) / 2              + 2 * mass_s * (r_s **2 + r_s **2) / 5
import numpy as np 

#density 
p = 5600
#mass of the cylindrical portion
r_c = 0.02
h = 0.20
#find the volume of the cylinder and multiply by the density
mass_c = np.pi * r_c **2 * h * p
#mass of the spheres
r_s = 0.10
#volume of the sphere and multiply by the desnity
mass_s = 4 * np.pi * r_s ** 3 / 3 * 5600

#we know konw the inertia matrix for both the recdtangle and the cylinger
irect = np.array([[mass_c * (3 * r_c **2 + h **2) / 12, 0, 0],
                  [0, mass_c * (3 * r_c **2 + h **2) / 12, 0],
                  [0, 0, mass_c * (r_c **2) / 2]])

isphere = np.array([[2 * mass_s * (r_s **2 + r_s **2) / 5, 0, 0],
                    [0, 2 * mass_s * (r_s **2 + r_s **2) / 5, 0],
                    [0, 0, 2 * mass_s * (r_s **2 + r_s **2) / 5]])

#rotate the spherical coordinates to align with those of the b frame
R_sb = np.array([[0, 0 , 1],
                 [1, 0 , 0],
                 [0, 1 , 0]])

#this is now the aligned spherical frame
aisphere = R_sb.T @ isphere @ R_sb
#left sphere & right sphere coordinates. Note that q = (0,0,z) of shape (1,3)
lq = np.array([0,0, .20])[None, :]
rq = np.array([0,0, -.20])[None,:]

lsphere = aisphere + mass_s * (lq.T @ lq @ np.identity(3) - lq @ lq.T)
rsphere = aisphere + mass_s * (rq.T @ rq @ np.identity(3) - rq @ rq.T)

print(irect + lsphere + rsphere )

[[-1.49643022 -1.87657801 -1.87657801]
 [-1.87657801 -1.49643022 -1.87657801]
 [-1.87657801 -1.87657801  0.37559709]]


In [77]:
lq.T @ lq @ np.identity(3)

array([[0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.04]])

In [54]:
theta = [0, np.pi/6, np.pi/4, np.pi/3, np.pi/2, 2*np.pi/3]
thetadot = [0.2, 0.2,  0.2, 0.2, 0.2, 0.2]
thetaddot = [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
g = [0, 0, -9.81]
vtip = [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]

M01 = [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0.089159], [0, 0, 0, 1]]
M12 = [[0, 0, 1, 0.28], [0, 1, 0, 0.13585], [-1, 0, 0, 0], [0, 0, 0, 1]]
M23 = [[1, 0, 0, 0], [0, 1, 0, -0.1197], [0, 0, 1, 0.395], [0, 0, 0, 1]]
M34 = [[0, 0, 1, 0], [0, 1, 0, 0], [-1, 0, 0, 0.14225], [0, 0, 0, 1]]
M45 = [[1, 0, 0, 0], [0, 1, 0, 0.093], [0, 0, 1, 0], [0, 0, 0, 1]]
M56 = [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0.09465], [0, 0, 0, 1]]
M67 = [[1, 0, 0, 0], [0, 0, 1, 0.0823], [0, -1, 0, 0], [0, 0, 0, 1]]
G1 = np.diag([0.010267495893, 0.010267495893,  0.00666, 3.7, 3.7, 3.7])
G2 = np.diag([0.22689067591, 0.22689067591, 0.0151074, 8.393, 8.393, 8.393])
G3 = np.diag([0.049443313556, 0.049443313556, 0.004095, 2.275, 2.275, 2.275])
G4 = np.diag([0.111172755531, 0.111172755531, 0.21942, 1.219, 1.219, 1.219])
G5 = np.diag([0.111172755531, 0.111172755531, 0.21942, 1.219, 1.219, 1.219])
G6 = np.diag([0.0171364731454, 0.0171364731454, 0.033822, 0.1879, 0.1879, 0.1879])
Glist = [G1, G2, G3, G4, G5, G6]
Mlist = [M01, M12, M23, M34, M45, M56, M67] 
Slist = [[0,         0,         0,         0,        0,        0],
         [0,         1,         1,         1,        0,        1],
         [1,         0,         0,         0,       -1,        0],
         [0, -0.089159, -0.089159, -0.089159, -0.10915, 0.005491],
         [0,         0,         0,         0,  0.81725,        0],
         [0,         0,     0.425,   0.81725,        0,  0.81725]]

mr.InverseDynamics(theta, thetadot, thetaddot, g, vtip, Mlist, Glist, Slist)

array([ 1.27670527e-02, -4.11476981e+01, -3.78093382e+00,  3.23099099e-02,
        3.69529049e-02,  1.03367459e-01])

In [10]:
#Use the function Screw Trajectory
x_start = np.identity(4)
x_end = np.array([[0, 0, 1, 1],
                  [1, 0, 0, 2],
                  [0, 1, 0, 3],
                  [0, 0, 0, 1]])
t_f = 10
N = 10
method = 3 

#calculate a trajectory with 10 discrete points between the start and end times. 
traj = mr.ScrewTrajectory(x_start, x_end, t_f, N = N, method=method)
trajCart = mr.CartesianTrajectory(x_start, x_end, t_f, N = N, method=5)

#calculate the current path parameter corresponding to a motion that begins and ends 
#with zero velocity and acceleration
s = mr.QuinticTimeScaling(5, 3)


0.6825599999999996


In [9]:
trajCart

[array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]),
 array([[ 0.99980553, -0.01384686,  0.01404133,  0.01153279],
        [ 0.01404133,  0.99980553, -0.01384686,  0.02306559],
        [-0.01384686,  0.01404133,  0.99980553,  0.03459838],
        [ 0.        ,  0.        ,  0.        ,  1.        ]]),
 array([[ 0.99148113, -0.08774296,  0.09626183,  0.07641112],
        [ 0.09626183,  0.99148113, -0.08774296,  0.15282223],
        [-0.08774296,  0.09626183,  0.99148113,  0.22923335],
        [ 0.        ,  0.        ,  0.        ,  1.        ]]),
 array([[ 0.93662474, -0.21400108,  0.27737633,  0.20987654],
        [ 0.27737633,  0.93662474, -0.21400108,  0.41975309],
        [-0.21400108,  0.27737633,  0.93662474,  0.62962963],
        [ 0.        ,  0.        ,  0.        ,  1.        ]]),
 array([[ 0.78284678, -0.31778776,  0.53494098,  0.3966875 ],
        [ 0.53494098,  0.78284678, -0.31778776,  0.79337499],
        [-0.31778776